#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port1,           ArmR,          tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           Right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           Right2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Right3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Lift,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Strafe,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Left1,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Left2,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Left3,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          ArmL,          tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              BURNSVIEW ROBOTICS                           */
/*                                                                           */
/*                          98549X VEX Brand Thermite                        */
/*                                                                           */
/*---------------------------------------------------------------------------*/


#pragma platform(VEX2)
#pragma competitionControl(Competition)

#define Num_Of_Auto_Modes 6

int nAutoModes = 0;
const string autoNames[] =
{
	"1 Left",
	"1 Right",
	"2 Left",
	"2 Right",
	"3 Forward",
	"3 Forward&Turn"
};

#include "Push_LCD_Tasks.c"
#include "Push_Competition_Includes.c"
#include "Push_Auto_Functions.c"
#include "Push_Auto1.c"
#include "Push_Auto2.c"
#include "Push_Auto3.c"

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  switch (nAutoModes)
  {
    case 0:
      auto1L();
      break;
    case 1:
      auto1R();
      break;
    case 2:
      auto2L();
      break;
    case 3:
      auto2R();
      break;
    case 4:
      auto3();
      break;
    case 5:
      auto3Turn();
      break;
    default:
      break;
  }
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	while (true)
	{
		if (vexRT[Btn7U])
		{
			motor[Left1] = vexRT[Ch3] + vexRT[Ch1] / 4;
			motor[Left2] = vexRT[Ch3] + vexRT[Ch1] / 4;
			motor[Left3] = vexRT[Ch3] + vexRT[Ch1] / 4;
			motor[Right1] = vexRT[Ch3] - vexRT[Ch1] / 4;
			motor[Right2] = vexRT[Ch3] - vexRT[Ch1] / 4;
			motor[Right3] = vexRT[Ch3] - vexRT[Ch1] / 4;
		}
		else
		{
			motor[Left1] = vexRT[Ch3] + vexRT[Ch1];
			motor[Left2] = vexRT[Ch3] + vexRT[Ch1];
			motor[Left3] = vexRT[Ch3] + vexRT[Ch1];
			motor[Right1] = vexRT[Ch3] - vexRT[Ch1];
			motor[Right2] = vexRT[Ch3] - vexRT[Ch1];
			motor[Right3] = vexRT[Ch3] - vexRT[Ch1];
		}

		if (vexRT[Btn7R])
		{
			motor[ArmL] = 115;
			wait1Msec(700);
		}

		if (vexRT[Btn8L])
		{
			motor[ArmR] = 115;
			wait1Msec(700);
		}

		if(vexRT[Btn7L] == 1)
			motor[Strafe] = 115;
		else if(vexRT[Btn8R] == 1)
			motor[Strafe] = -115;
		else
			motor[Strafe] = 0;

		if(vexRT[Btn5U] == 1)
			motor[ArmL] = 115;
		else if(vexRT[Btn5D] == 1)
			motor[ArmL] = -115;
		else
			motor[ArmL] = 0;

		if(vexRT[Btn6U] == 1)
			motor[ArmR] = 115;
		else if(vexRT[Btn6D] == 1)
			motor[ArmR] = -115;
		else
			motor[ArmR] = 0;

		if (vexRT[Btn8U])
			motor[Lift] = 115;
		else if (vexRT[Btn8D])
			motor[Lift] = -115;
		else
			motor[Lift] = 0;

	}
}
